### ISSUE TITLE
Android package installer unable to parse file for 0.2a

### ISSUE THREAD

**Issue by VikOlliver** [gsantner/dandelion#126]
#### General information

* **Device:**   Samsung Galaxy GT-N5120
* **Android Version:**  4.1.2
* **App version:** 0.2a (attempted)
* **App source:**  
* **Pod:**  
* **Diaspora pod version:**  

#### Steps to reproduce

Download apk from release archive page 
 
https://github.com/Diaspora-for-Android/diaspora-android/releases/download/v0.2.0a/DiasporaForAndroid__0.2.0a__-release.apk

Attempt to install with either Android or Google+ installer

#### Expected result
**What is the expected output?** 
Installed app.

**What do you see instead?**

"There is a problem parsing the package"

**Comment by vanitasvitae** [comment]
The minimum supported android version is 4.2 unfortunatelly :/

**Comment by gsantner** [comment]
Thanks for your report!

@VikOlliver Android 4.1.2 is API level 16, we support minimum level 17, because of many security reasons.
E.g. anyone could put some bad javascript in the content, and may harm your phone.
Your version is really old, I recommend you to upgrade if available or buy a new one if security and privacy is something worth for you (it should be!) .
