### ISSUE TITLE
optimize display options

### ISSUE THREAD

**Issue by lupa18** [gsantner/dandelion#128]
I think would be great (for courtiers with lore bandwidth) to make 2 adjustments to displaying articles:
1. Display images but reduced. Now they display in high resolution (is: 2 or more mb). In the future would be great size were < 1mb

2. Show reduced articles like official web. There I see kind of excerpt while here I see long articles

Thanks for considering

**Comment by vanitasvitae** [comment]
Im affraid there's not much we can do here.
Since images in posts are not available in lower resolutions, we can not load smaller versions.

The second point is also nothing we can really change. You can try to convince the diaspora\* team to make changes to the mobile website of diaspora, since that is what we are displaying.

Anyway thank you for your input :)

**Comment by gsantner** [comment]
You can uncheck the "Load images" option in the settings, but this way you won't get any images at all.
...but it will save a lot of data
