### ISSUE TITLE
cannot be installed on jolla.

### ISSUE THREAD

**Issue by norayr** [gsantner/dandelion#144]
#### General information

* **Device:**   Jolla
* **Android Version:**  aliendalvik-0.17.35
* **App version:**  not installed
* **App source:**  F-Droid
* **Pod:**  
* **Diaspora pod version:**  

dandelion is not installable on Jolla device with f-droid. There's no 'install' button. This happens with software which requirements are higher than actual. I don't know which requirements Jolla does not correspond, is that aliandalvik, or hardware(less probably). But diaspora users often use Jolla phone, so it would be cool if dandelion would work on Jolla phones.

#### Steps to reproduce

1. Open f-droid and find dandelion, try to install.

#### Expected result
**What is the expected output?** 

**What do you see instead?**
Absent 'install' button.

Upload screenshots via drag&drop if needed and apply resizing:
![image](https://cloud.githubusercontent.com/assets/11881650/23063162/7e0cd27a-f522-11e6-8788-bec54efee25a.png)

that is all folks.

**Comment by gsantner** [comment]
That means the Android Runtime implementation on your device is below v4.2.2. 
We don't and won't support such old versions, because of many security reasons.
I don't have any Jolla device or know much about their Android Runtime Implementations, but as far I know there are some available with 4.4. which would be supported. 

Sorry, either upgrade your device if an update is available or buy a newer device.
The README clearly mentions absolute minium required specifications, which your device don't match.
