### ISSUE TITLE
Pull down & refresh trigger is too sensitive

### ISSUE THREAD

**Issue by stragu** [gsantner/dandelion#33]
#### General information
- **Device:** Fairphone 1
- **Android Version:** 4.2.2
- **Pod:** joindiaspora.com
- **Diaspora pod version:** 0.5.9.99
- **App source:** F-Droid
- **App version:** 0.1.2

I have:
- [x] searched open and closed issues for duplicates
- [x] Diaspora for Android installed with an version >= 0.1.1
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce
1. Go to your stream
2. Pull down to get back to the top
#### Expected result

The refresh trigger is very sensitive and starts as soon as we reach the top of the stream. The trigger should not be as sensible so we don't refresh all the time without wanting to.
#### Debug output

N/A

**Comment by 4ndyD** [comment]
Using same 0.1.2, same pod, on a FP2, Open OS 16.06.0 (Android 5.1 base), I find this is very problematic when trying to write a new post, and attempting to scroll up in the (very undersized - another issue) text box causes the page to refresh and wipe everything that I wrote.

This problem was so annoying when writing something of significant length that I resorted to plugging a USB keyboard into my phone so that I could quickly select all & copy for safety, and ctrl+home to go up.
By doing so I also discovered that the writing cursor is allowed to escape the text box and select (without activating) the buttons when pressing arrow keys at either end of the text entered. I would expect that behaviour only from a tab key but am not sure if I would call that a bug.

**Comment by gsantner** [comment]
I already put code in for NEW conversations some time ago. Should be easy to also enable for existing conversations.

https://github.com/Diaspora-for-Android/diaspora-android/blob/master/app/src/main/java/com/github/dfa/diaspora_android/ui/CustomWebViewClient.java#L41

**Comment by vanitasvitae** [comment]
> By doing so I also discovered that the writing cursor is allowed to escape the text box and select (without activating) the buttons when pressing arrow keys at either end of the text entered. I would expect that behaviour only from a tab key but am not sure if I would call that a bug.

I'm not sure, whether this behavior is caused by the app, or if it is a bug in the Android WebView. We'll have to investigate this.

The original issue is a duplicate though.
