### ISSUE TITLE
App with new package on F-Droid

### ISSUE THREAD

**Issue by gsantner** [gsantner/dandelion#5]
Contact F-Droid team and get the app with the new ID into the repo.

**Comment by gsantner** [comment]
https://github.com/Diaspora-for-Android/diaspora-android/issues/2#issuecomment-203036643

**Comment by ghost** [comment]
I really think it was a quite bad decision to change the package name and dump down the version code. Even if the app name or team changes, breaking update for end users is a no-go -- especially since we have NO WAY to inform existing users about a change. The procedure we did for a small number of apps already:

1) Build new app with new id.
2) Release a last version with existing package id that show an infobox on startup that points to the new app.
3) Add deprecation notice on the old app metadata.
4) Move old app to the repo after some time.

If you want to go the extra mile for both apps is up to you.

**Comment by ghost** [comment]
Added deprecation notices and the new build in https://gitlab.com/fdroid/fdroiddata/commit/532f2838425468e6bb5d4a8deaae850aaeeb7bed.

**Comment by gsantner** [comment]
@krt16s Thanks for your hard work!
App is now downloadable on F-Droid. https://f-droid.org/repository/browse/?fdid=com.github.dfa.diaspora_android

**Comment by ghost** [comment]
Would still love to hear back if it's planned to release a last version using the former package ids or if i should just move it to the archive without noticing the users.

**Comment by mdev88** [comment]
We decided to change the package name knowing updates would be broken. 
We wanted this new project to be a "start from scrach" in a lot of ways and not necessarily a continuation on two projects that both had several issues by design. 
We are going to be announcing the transition between the Disapora Native Webapp and Scoute dichs' fork to this one when we have a release we are comfortable publishing via the usual channels.

**Comment by ghost** [comment]
Hi @krt16s 

Here the same. I will release an update with an alert dialog, that points to the new app. I will write also that the new app is still in beta stage. Once we have a more or less stable release I wil make the last update.

Thanks for your work and patience.

**Comment by gsantner** [comment]
@krt16s Version v0.1.1 was released today, the old Diaspora\* Android apps which received their last update over a month ago can now be moved over to the "F-Droid Archive", so it's clear for new users that they should download this app.  

Thanks, and kind regards
