### ISSUE TITLE
Implement password/pin code lock

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#57]
It would be nice, to have an option to activate a pin or password code that prevents unauthorized people from viewing contents of the app. This would of course be an optional feature.

**Comment by issueseverywhere** [comment]
It would actually be very useful to have a password code/lock in dandelion, so that you don't have to go through all the "disconnect and reconnect" process if you just want to leave your phone somewhere or to someone who just wants to use your phone for something else for a moment. Signal implements it and it is very easy to use from the notification bar.
