### ISSUE TITLE
Add option to add followed hashtag to followed-hashtag-overview

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#66]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** (latest HEAD)
- **App version:** HEAD

#### Steps to reproduce
1. Click on "Followed Hashtags" in navigation drawer
#### Expected result

What is the expected output? 
Hashtag overview shows a button or something that allows the user to follow an additional hashtag

What do you see instead?
Only a list of hashtags

I know, that the user is supposed to follow a hashtag by searching for it and then click "Follow XYZ" on top of the stream, but thats kinda contra intuitive.

**Comment by gsantner** [comment]
Not possible without API, or a proper implementation in the mobile view.
For a proper implementation we have to wait for methods in the diaspora API allowing this.

**Comment by vanitasvitae** [comment]
What we can do though is add a edit-button to the hashtags fragment, that opens the manage-hashtags-url in the webview.

**Comment by gsantner** [comment]
I don't see any benefit on this.
<img src="https://cloud.githubusercontent.com/assets/6735650/19784213/32c321d8-9c95-11e6-833d-e905f6b12ca1.jpg" width="30%" height="30%" />
Because all you can do at the manage tags, is to unfollow. And that can also be done by clicking on a tab in the current TagsFragments and clicking Unfollow. What could be done is to add an search box which goes to the tag. But this may break the intelliHide stuff again.

**Comment by vanitasvitae** [comment]
I guess you're right :D

**Comment by gsantner** [comment]
As said, when searching for a specific tag, you will get a preview whats posted with this tag,and can follow the tag.
Closing.
